### PR TITLE
Layout fixes

### LINKED ISSUE #541: Visual layout fixes
- Disabled buttons color to lighter
- More rounded corners for cards and elevation 
- Check layout on individual pages and adjust paddings and spacings where needed

### PR DESCRIPTION
**Pull request by leinson**
- Fixed arrow button colour to have a lighter disabled colour
- Added padding to summary pages in the role cards
- Uniform style of cards with rounded corners and elevation
- Transparent background to the header text on the frontpage to make it more readable

Closes #541

### CODE REVIEW

File: frontend/src/components/roleSurvey/GroupAccordion.jsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ import GroupForm from '../GroupForm'
 
 const GroupAccordion = () => {
     return (
-        <Accordion>
+        <Accordion >
```
Comment (trickwide) [inline frontend/src/components/roleSurvey/GroupAccordion.jsx:14]:
```suggestion
        <Accordion>
```

**Review by trickwide — APPROVED** [review]
Good job, these changes truly **elevated** the visual aspect of the website to a whole new level! LGTM :shipit:
